title: jasty.dev
author:
  name: "Jack Weinstein"
  email: blog@jasty.dev
description: >-
  Look, I made a thing!
url: https://jasty.dev
domain: jasty.dev
social:
  github: weinstein
  linkedin: jhsw93
rss: rss

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

google_analytics: G-2D5VCWZTBJ

collections:
  games:
    output: true
