title: jasty.dev
author:
  name: "Jack Weinstein"
  email: blog@jasty.dev
description: >-
  Look, I made a thing!
url: https://jasty.dev
domain: jasty.dev
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/weinstein" }
    - { platform: linkedin, user_url: "https://linkedin.com/jhsw93" }
rss: rss

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

google_analytics: G-2D5VCWZTBJ

collections:
  games:
    output: true
