name: website

static_sites:
- name: static
  environment_slug: html
  github:
    repo: weinstein/website
    branch: main
    deploy_on_push: true
  source_dir: static
  index_document: index.html
  error_document: error.html
  routes:
  - path: /
